services:
  - type: web
    name: game-bot-backend
    runtime: docker
    repo: https://github.com/Whvra/Game.git
    branch: main
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_DEFAULT_CHANNEL_ID
        sync: false
      - key: GAME_PLAY_URL
        value: https://game-5iha.onrender.com/
    autoDeploy: true
